// This file is automatically generated. Do not edit it directly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      bookings: {
        Row: {
          cancelled_at: string | null
          cancelled_reason: string | null
          completed_at: string | null
          created_at: string
          created_by_role: string
          created_by_user_id: string | null
          customer_email: string | null
          customer_name: string
          customer_phone: string
          end_at: string
          id: string
          merchant_id: string
          notes: string | null
          service_item_id: string
          source: string
          staff_id: string
          start_at: string
          status: string
          updated_at: string
        }
        Insert: {
          cancelled_at?: string | null
          cancelled_reason?: string | null
          completed_at?: string | null
          created_at?: string
          created_by_role: string
          created_by_user_id?: string | null
          customer_email?: string | null
          customer_name: string
          customer_phone: string
          end_at: string
          id?: string
          merchant_id: string
          notes?: string | null
          service_item_id: string
          source?: string
          staff_id: string
          start_at: string
          status?: string
          updated_at?: string
        }
        Update: {
          cancelled_at?: string | null
          cancelled_reason?: string | null
          completed_at?: string | null
          created_at?: string
          created_by_role?: string
          created_by_user_id?: string | null
          customer_email?: string | null
          customer_name?: string
          customer_phone?: string
          end_at?: string
          id?: string
          merchant_id?: string
          notes?: string | null
          service_item_id?: string
          source?: string
          staff_id?: string
          start_at?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "bookings_merchant_id_fkey"
            columns: ["merchant_id"]
            isOneToOne: false
            referencedRelation: "merchants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_service_item_id_fkey"
            columns: ["service_item_id"]
            isOneToOne: false
            referencedRelation: "service_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_staff_id_fkey"
            columns: ["staff_id"]
            isOneToOne: false
            referencedRelation: "merchant_staff"
            referencedColumns: ["id"]
          },
        ]
      }
      groups: {
        Row: {
          created_at: string
          group_admin_user_id: string | null
          id: string
          name: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          group_admin_user_id?: string | null
          id?: string
          name?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          group_admin_user_id?: string | null
          id?: string
          name?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      industry_feature_presets: {
        Row: {
          default_enabled: boolean
          feature_key: string
          id: string
          industry_type: string
        }
        Insert: {
          default_enabled: boolean
          feature_key: string
          id?: string
          industry_type: string
        }
        Update: {
          default_enabled?: boolean
          feature_key?: string
          id?: string
          industry_type?: string
        }
        Relationships: []
      }
      merchant_admins: {
        Row: {
          created_at: string
          id: string
          merchant_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          merchant_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          merchant_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "merchant_admins_merchant_id_fkey"
            columns: ["merchant_id"]
            isOneToOne: false
            referencedRelation: "merchants"
            referencedColumns: ["id"]
          },
        ]
      }
      merchant_agent_permissions: {
        Row: {
          agent_id: string
          created_at: string
          granted: boolean
          id: string
          section_key: string
          updated_at: string
        }
        Insert: {
          agent_id: string
          created_at?: string
          granted?: boolean
          id?: string
          section_key: string
          updated_at?: string
        }
        Update: {
          agent_id?: string
          created_at?: string
          granted?: boolean
          id?: string
          section_key?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "merchant_agent_permissions_agent_id_fkey"
            columns: ["agent_id"]
            isOneToOne: false
            referencedRelation: "merchant_agents"
            referencedColumns: ["id"]
          },
        ]
      }
      merchant_agents: {
        Row: {
          activated_at: string | null
          contact_email: string | null
          created_at: string
          id: string
          invited_at: string
          invited_email: string
          merchant_id: string
          name: string
          nickname: string | null
          phone: string | null
          status: string
          updated_at: string
          user_id: string | null
        }
        Insert: {
          activated_at?: string | null
          contact_email?: string | null
          created_at?: string
          id?: string
          invited_at?: string
          invited_email: string
          merchant_id: string
          name: string
          nickname?: string | null
          phone?: string | null
          status?: string
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          activated_at?: string | null
          contact_email?: string | null
          created_at?: string
          id?: string
          invited_at?: string
          invited_email?: string
          merchant_id?: string
          name?: string
          nickname?: string | null
          phone?: string | null
          status?: string
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "merchant_agents_merchant_id_fkey"
            columns: ["merchant_id"]
            isOneToOne: false
            referencedRelation: "merchants"
            referencedColumns: ["id"]
          },
        ]
      }
      merchant_business_hours: {
        Row: {
          close_time: string | null
          created_at: string
          day_of_week: number
          id: string
          is_closed: boolean
          merchant_id: string
          open_time: string | null
          updated_at: string
        }
        Insert: {
          close_time?: string | null
          created_at?: string
          day_of_week: number
          id?: string
          is_closed?: boolean
          merchant_id: string
          open_time?: string | null
          updated_at?: string
        }
        Update: {
          close_time?: string | null
          created_at?: string
          day_of_week?: number
          id?: string
          is_closed?: boolean
          merchant_id?: string
          open_time?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "merchant_business_hours_merchant_id_fkey"
            columns: ["merchant_id"]
            isOneToOne: false
            referencedRelation: "merchants"
            referencedColumns: ["id"]
          },
        ]
      }
      merchant_feature_flags: {
        Row: {
          created_at: string
          enabled: boolean
          feature_key: string
          id: string
          merchant_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          enabled: boolean
          feature_key: string
          id?: string
          merchant_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          enabled?: boolean
          feature_key?: string
          id?: string
          merchant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "merchant_feature_flags_merchant_id_fkey"
            columns: ["merchant_id"]
            isOneToOne: false
            referencedRelation: "merchants"
            referencedColumns: ["id"]
          },
        ]
      }
      merchant_staff: {
        Row: {
          advance_booking_days: number | null
          auto_accept_booking: boolean
          avatar_url: string | null
          booking_window_max_days: number | null
          booking_window_min_days: number | null
          can_create_edit_orders: boolean
          can_upload_construction_photos: boolean
          contact_email: string | null
          created_at: string
          direct_accept_after_merchant_confirm: boolean
          google_calendar_sync_enabled: boolean
          id: string
          intro: string | null
          is_listed: boolean
          line_bound: boolean
          line_user_id: string | null
          merchant_id: string
          name: string
          nickname: string | null
          no_time_slot_limit: boolean
          phone: string | null
          show_member_info: boolean
          status: string
          unlimited_backend_edit: boolean
          updated_at: string
          user_id: string | null
        }
        Insert: {
          advance_booking_days?: number | null
          auto_accept_booking?: boolean
          avatar_url?: string | null
          booking_window_max_days?: number | null
          booking_window_min_days?: number | null
          can_create_edit_orders?: boolean
          can_upload_construction_photos?: boolean
          contact_email?: string | null
          created_at?: string
          direct_accept_after_merchant_confirm?: boolean
          google_calendar_sync_enabled?: boolean
          id?: string
          intro?: string | null
          is_listed?: boolean
          line_bound?: boolean
          line_user_id?: string | null
          merchant_id: string
          name: string
          nickname?: string | null
          no_time_slot_limit?: boolean
          phone?: string | null
          show_member_info?: boolean
          status?: string
          unlimited_backend_edit?: boolean
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          advance_booking_days?: number | null
          auto_accept_booking?: boolean
          avatar_url?: string | null
          booking_window_max_days?: number | null
          booking_window_min_days?: number | null
          can_create_edit_orders?: boolean
          can_upload_construction_photos?: boolean
          contact_email?: string | null
          created_at?: string
          direct_accept_after_merchant_confirm?: boolean
          google_calendar_sync_enabled?: boolean
          id?: string
          intro?: string | null
          is_listed?: boolean
          line_bound?: boolean
          line_user_id?: string | null
          merchant_id?: string
          name?: string
          nickname?: string | null
          no_time_slot_limit?: boolean
          phone?: string | null
          show_member_info?: boolean
          status?: string
          unlimited_backend_edit?: boolean
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "merchant_staff_merchant_id_fkey"
            columns: ["merchant_id"]
            isOneToOne: false
            referencedRelation: "merchants"
            referencedColumns: ["id"]
          },
        ]
      }
      merchant_staff_service_items: {
        Row: {
          created_at: string
          id: string
          service_item_id: string
          staff_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          service_item_id: string
          staff_id: string
        }
        Update: {
          created_at?: string
          id?: string
          service_item_id?: string
          staff_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "merchant_staff_service_items_service_item_id_fkey"
            columns: ["service_item_id"]
            isOneToOne: false
            referencedRelation: "service_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "merchant_staff_service_items_staff_id_fkey"
            columns: ["staff_id"]
            isOneToOne: false
            referencedRelation: "merchant_staff"
            referencedColumns: ["id"]
          },
        ]
      }
      merchants: {
        Row: {
          address: string | null
          announcement_content: string | null
          announcement_enabled: boolean
          booking_slug: string | null
          contact_email: string | null
          created_at: string
          group_id: string
          id: string
          industry_type: string
          intro: string | null
          logo_url: string | null
          name: string
          status: string
          theme_custom_color: string | null
          theme_preset: string | null
          updated_at: string
        }
        Insert: {
          address?: string | null
          announcement_content?: string | null
          announcement_enabled?: boolean
          booking_slug?: string | null
          contact_email?: string | null
          created_at?: string
          group_id: string
          id?: string
          industry_type: string
          intro?: string | null
          logo_url?: string | null
          name: string
          status?: string
          theme_custom_color?: string | null
          theme_preset?: string | null
          updated_at?: string
        }
        Update: {
          address?: string | null
          announcement_content?: string | null
          announcement_enabled?: boolean
          booking_slug?: string | null
          contact_email?: string | null
          created_at?: string
          group_id?: string
          id?: string
          industry_type?: string
          intro?: string | null
          logo_url?: string | null
          name?: string
          status?: string
          theme_custom_color?: string | null
          theme_preset?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "merchants_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
        ]
      }
      platform_admins: {
        Row: {
          created_at: string
          id: string
          note: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          note?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          note?: string | null
          user_id?: string
        }
        Relationships: []
      }
      service_categories: {
        Row: {
          created_at: string
          id: string
          merchant_id: string
          name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          merchant_id: string
          name: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          merchant_id?: string
          name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_categories_merchant_id_fkey"
            columns: ["merchant_id"]
            isOneToOne: false
            referencedRelation: "merchants"
            referencedColumns: ["id"]
          },
        ]
      }
      service_items: {
        Row: {
          category_id: string | null
          created_at: string
          duration_minutes: number
          id: string
          item_type: string
          merchant_id: string
          name: string
          price: number
          status: string
          updated_at: string
        }
        Insert: {
          category_id?: string | null
          created_at?: string
          duration_minutes: number
          id?: string
          item_type: string
          merchant_id: string
          name: string
          price: number
          status?: string
          updated_at?: string
        }
        Update: {
          category_id?: string | null
          created_at?: string
          duration_minutes?: number
          id?: string
          item_type?: string
          merchant_id?: string
          name?: string
          price?: number
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_items_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_items_merchant_id_fkey"
            columns: ["merchant_id"]
            isOneToOne: false
            referencedRelation: "merchants"
            referencedColumns: ["id"]
          },
        ]
      }
      staff_availability_windows: {
        Row: {
          created_at: string
          day_of_week: number
          end_time: string
          id: string
          staff_id: string
          start_time: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          day_of_week: number
          end_time: string
          id?: string
          staff_id: string
          start_time: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          day_of_week?: number
          end_time?: string
          id?: string
          staff_id?: string
          start_time?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "staff_availability_windows_staff_id_fkey"
            columns: ["staff_id"]
            isOneToOne: false
            referencedRelation: "merchant_staff"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      am_i_merchant_admin: { Args: { p_merchant_id: string }; Returns: boolean }
      am_i_platform_admin: { Args: never; Returns: boolean }
      apply_industry_preset: {
        Args: { p_merchant_id: string }
        Returns: undefined
      }
      cancel_booking: {
        Args: { p_booking_id: string; p_reason?: string }
        Returns: {
          cancelled_at: string | null
          cancelled_reason: string | null
          completed_at: string | null
          created_at: string
          created_by_role: string
          created_by_user_id: string | null
          customer_email: string | null
          customer_name: string
          customer_phone: string
          end_at: string
          id: string
          merchant_id: string
          notes: string | null
          service_item_id: string
          source: string
          staff_id: string
          start_at: string
          status: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "bookings"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      complete_booking: {
        Args: { p_booking_id: string }
        Returns: {
          cancelled_at: string | null
          cancelled_reason: string | null
          completed_at: string | null
          created_at: string
          created_by_role: string
          created_by_user_id: string | null
          customer_email: string | null
          customer_name: string
          customer_phone: string
          end_at: string
          id: string
          merchant_id: string
          notes: string | null
          service_item_id: string
          source: string
          staff_id: string
          start_at: string
          status: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "bookings"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      create_booking: {
        Args: {
          p_customer_email?: string
          p_customer_name: string
          p_customer_phone: string
          p_merchant_id: string
          p_notes?: string
          p_service_item_id: string
          p_staff_id: string
          p_start_at: string
        }
        Returns: {
          cancelled_at: string | null
          cancelled_reason: string | null
          completed_at: string | null
          created_at: string
          created_by_role: string
          created_by_user_id: string | null
          customer_email: string | null
          customer_name: string
          customer_phone: string
          end_at: string
          id: string
          merchant_id: string
          notes: string | null
          service_item_id: string
          source: string
          staff_id: string
          start_at: string
          status: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "bookings"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      create_group_and_merchant: {
        Args: {
          p_address?: string
          p_contact_email?: string
          p_industry_type: string
          p_intro?: string
          p_name: string
        }
        Returns: string
      }
      create_merchant_in_group: {
        Args: {
          p_address?: string
          p_contact_email?: string
          p_group_id: string
          p_industry_type: string
          p_intro?: string
          p_name: string
        }
        Returns: string
      }
      generate_booking_slug: { Args: { p_name: string }; Returns: string }
      get_merchant_admin_users: {
        Args: { p_merchant_id: string }
        Returns: {
          created_at: string
          email: string
          id: string
          merchant_id: string
          user_id: string
        }[]
      }
      get_merchant_day_schedule: {
        Args: { p_date: string; p_merchant_id: string }
        Returns: Json
      }
      invite_merchant_admin: {
        Args: { p_merchant_id: string; p_user_email: string }
        Returns: undefined
      }
      lookup_user_id_by_email: { Args: { p_email: string }; Returns: string }
      mark_agent_active_if_self: { Args: never; Returns: undefined }
      platform_add_merchant_admin: {
        Args: { p_merchant_id: string; p_user_email: string }
        Returns: undefined
      }
      platform_get_merchant_admin_counts: {
        Args: never
        Returns: {
          admin_count: number
          merchant_id: string
        }[]
      }
      platform_get_user_email: { Args: { p_user_id: string }; Returns: string }
      platform_remove_merchant_admin: {
        Args: { p_merchant_id: string; p_user_id: string }
        Returns: undefined
      }
      platform_set_group_admin: {
        Args: { p_group_id: string; p_user_email: string }
        Returns: undefined
      }
      record_invited_merchant_agent: {
        Args: {
          p_invited_email: string
          p_merchant_id: string
          p_name: string
          p_nickname: string
          p_phone: string
          p_status: string
          p_user_id: string
        }
        Returns: string
      }
      remove_merchant_admin: {
        Args: { p_merchant_id: string; p_user_id: string }
        Returns: undefined
      }
      remove_merchant_agent: {
        Args: { p_agent_id: string }
        Returns: undefined
      }
      set_agent_permission: {
        Args: { p_agent_id: string; p_granted: boolean; p_section_key: string }
        Returns: undefined
      }
      storage_path_merchant_id: { Args: { p_path: string }; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const

